#!/bin/bash
options_found=0
echo ""
echo "SMB Null Login Check Script"
echo "Version 1.0.2"
echo "Written by Rogu3Panda"
echo ""
echo "Script Purpose: Attempt to perform SMB Login"
echo "Using Blank Username and No Password"
while getopts ":ht:o:" opt;do

  options_found=1

    case $opt in
	t)
	  TARGET_FILE=${OPTARG}
	    if [ ${TARGET_FILE: -4} != ".txt" ];then
		echo "[*] Error: Please enter in a file containing targets with a .txt extension"
			exit 1
	    fi
	    ;;
         o)
           OUTPUT_FILE=${OPTARG}
           if [ ${OUTPUT_FILE: -4} != ".txt" ];then
             echo "[*] ERROR: Please enter in a output file"
             exit 1
           fi
           ;;
	h)
	  echo "Help Command"
	  echo "Usage: ./SMB_Null.sh [options]"
	  echo "Options:"
	  echo "-t <Target_File.txt>"
	  exit 1
	  ;;
    esac
done

if ((!options_found));then
	echo ""
	echo "Please enter in the appropriate optoins"
	exit 0
fi

for ip in $(cat $TARGET_FILE);do
	echo "Checking for Null Session on Host: $ip" 2>&1 | tee -a $OUTPUT_FILE
	rpcclient -U "" -N $ip 2>&1 | tee -a $OUTPUT_FILE
done
exit 0
